version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20 # Correctly specify the Docker version if needed
    commands:
      - echo Installing Docker...
      - docker --version
  pre_build:
    commands:
      - echo Starting the build process...
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t my-image .
  post_build:
    commands:
      - echo Build completed!
artifacts:
  files:
    - '**/*'
